metaphor-go:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    hosts:
      - host: metaphor-go-production.
        paths:
          - /
    tls:
    - secretName: metaphor-go-tls
      hosts:
        - metaphor-go-production.
  vaultMountPoint: kubefirst
  vaultSecretPath: production/metaphor
