apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubefirst-api
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://kubefirst.github.io/charts
    targetRevision: 0.1.2
    chart: api
    helm:
      values: |-
        env:
          KUBEFIRST_VERSION:
            value: "1.10.1"
          HOSTED_ZONE_NAME:
            value: ""
  destination:
    server: https://kubernetes.default.svc
    namespace: kubefirst
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

