apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubefirst-console
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://kubefirst.github.io/charts
    targetRevision: 1.0.2
    chart: console
    helm:
      values: |-
        env:
          ADMIN_EMAIL:
            value: ""
          CLUSTER_NAME:
            value: "kubefirst"
          HOSTED_ZONE_NAME:
            value: ""
          GITHUB_HOST:
            value: "github.com"
          GITHUB_OWNER:
            value: "tehonion"
        ingress:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: kubefirst
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
