apiVersion: v2
dependencies:
- name: metaphor-go
  repository: https://chartmuseum.
  version: 0.0.1-rc.f616e90
description: metaphor go instance
name: metaphor-go-staging
type: application
version: 1.0.0
