metaphor-frontend:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    hosts:
      - host: metaphor-frontend-production.
        paths:
          - /
    tls:
    - secretName: metaphor-frontend-tls
      hosts:
        - metaphor-frontend-production.

metaphor:
  host: metaphor-production.

metaphorGo:
  host: metaphor-go-production.

